project:
  type: book
  output-dir: _book

book:
  title: "R Booster"
  author: "Research Data Management Support<br>Utrecht University"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

  repo-url: https://github.com/UtrechtUniversity/workshop-r-booster
  repo-actions: [edit]

bibliography: references.bib

format:
  html:
    theme: cosmo

callout-appearance: simple
